### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by davidEthika** [gideonn/objectify#2]
Hey there, I can't even upload a photo of a flower to your app.

**Comment by gideonn** [comment]
Hi,
What is the image extension and size of the image ?

**Comment by Deg5112** [comment]
.jpeg file downloaded from the first page of google images when searching for ‘flower’

**Comment by gideonn** [comment]
Can you upload the image with your issue, that'll help me see what's wrong with the file.

**Comment by Deg5112** [comment]
![Uploading pexels-photo-96918.jpeg…]()

**Comment by gideonn** [comment]
Umm that isn't a file, you can use the github file uploader to upload the file.

**Comment by Deg5112** [comment]
https://static.pexels.com/photos/96918/pexels-photo-96918.jpeg

**Comment by gideonn** [comment]
Just what I thought, the image size is 10MB. Google Vision API rejects images of huge sizes so that it doesn't hog the server.

Try uploading images in KBs or <4 MBs

**Comment by Deg5112** [comment]
Or.. you can programmatically resize the image to provide the best user experience. The average user won't look for an image of a certain size then upload it to your app. Or have a better error message for the user then just.. internal server error

**Comment by gideonn** [comment]
Yup, that **should** be done. 
I made this app in 2 days, and it needs to go through multiple iterations of error handling and stuff.

**Comment by gideonn** [comment]
Image file size issue has been fixed now. You can try with the same image of 10 MB.
Let me know if it fails in any scenario other than the image having right extension.

**Comment by gideonn** [comment]
Added info regarding allowed file extensions too.
